name: grafana-release
services:
  nginx:
    image: emit5/nginx-grafana:latest
    container_name: nginx
    restart: always
    environment:
      - GF_PASSWORD=${GF_PASSWORD}
      - DASHBOARD_UID=${DASHBOARD_UID}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PUBLIC_PORT_TLS=${PUBLIC_PORT_TLS}
    ports:
      - "${PUBLIC_PORT}:80"
      - "${PUBLIC_PORT_TLS}:443"
    depends_on:
      - grafana
      - vat
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

  grafana:
    image: emit5/grafana-release:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  vat:
    image: emit5/vat-invoice:6065fdf8047ff554a3d2c82e0d9ec197a0fb28c3
    container_name: vat
    restart: always
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
