name: grafana-test
services:
  nginx:
    image: nginx-test:latest
    container_name: nginx
    restart: always
    environment:
      - GF_PASSWORD=${GF_PASSWORD}
      - DASHBOARD_UID=${DASHBOARD_UID}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PUBLIC_PORT_TLS=${PUBLIC_PORT_TLS}
    ports:
      - "${PUBLIC_PORT}:80"
    depends_on:
      - grafana
      - vat

  grafana:
    image: grafana-test:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource,grafana-clock-panel
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '3000:3000'

  vat:
    image: emit5/vat-invoice:6065fdf8047ff554a3d2c82e0d9ec197a0fb28c3
    container_name: vat
    restart: always
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
