{
 "title": "Demo Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Carbon intensity rating (all-time)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select 100.0*count(*)/(select count(*) from carbonintensityrecord) as value, rating as metric from carbonintensityrecord group by rating;",
     "rawQueryText": "select 100.0*count(*)/(select count(*) from carbonintensityrecord) as value, rating as metric from carbonintensityrecord group by rating;",
     "rawSql": "select 100.0*count(*)/(select count(*) from carbonintensityrecord) as value, rating as metric from carbonintensityrecord group by rating;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Carbon intensity: forecast vs actual",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT forecast, actual from carbonintensityrecord order by time desc limit 100;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "#### GitHub links\n\n- Data acquisition using AWS Lambda: [github.com/e-mit/aws-lambda-get](https://github.com/e-mit/aws-lambda-get)\n- Data validation using AWS Lambda, SQS, SQLModel: [github.com/e-mit/aws-lambda-db](https://github.com/e-mit/aws-lambda-db)\n- Setup AWS EC2 and RDS with PostgreSQL: [github.com/e-mit/aws-postgres](https://github.com/e-mit/aws-postgres)\n- Grafana configuration and Docker build: [github.com/e-mit/grafana-docker](https://github.com/e-mit/grafana-docker)\n\n\nData source: [carbonintensity.org.uk](https://carbonintensity.org.uk/)"
   }
  },
  {
   "title": "Carbon intensity (actual, last 7 days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select time, actual from carbonintensityrecord order by time desc limit 100;"
    }
   ]
  }
 ]
}