# syntax=docker/dockerfile:1

FROM nginx as base

RUN apt-get update
RUN apt-get install -y jq
RUN rm -rf /var/cache/apt/lists

WORKDIR /

COPY start.sh start.sh
COPY nginx-custom.conf nginx-custom.conf
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.old
RUN mv /etc/nginx/nginx.conf /etc/nginx/old
COPY nginx.conf /etc/nginx/nginx.conf

CMD ./start.sh
