# syntax=docker/dockerfile:1

FROM nginx as base

RUN apt-get update
RUN apt-get install -y jq
RUN rm -rf /var/cache/apt/lists

WORKDIR /

COPY start.sh start.sh
COPY 503.html /usr/share/nginx/html/503.html
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.old
RUN mv /etc/nginx/nginx.conf /etc/nginx/old
COPY nginx.conf /etc/nginx/nginx.conf

FROM base as release
# Conf includes TLS
COPY nginx-custom-release.conf nginx-custom.conf
CMD ./start.sh

FROM base as test
# Conf does not include TLS
COPY nginx-custom-test.conf nginx-custom.conf
CMD ./start.sh
