name: download-docker-artifact
description: "Download the built docker image"

inputs:
   repo-read-token:
     required: true
     description: "A GitHub PAT with actions:read permission on this repo."
   build-type:
     required: true
     description: "'test' or 'release'"
     default: 'test'

runs:
  using: "composite"
  steps:
  - name: Wait for docker image artifact
    shell: bash
    run: |
      export GITHUB_SHA=${{ github.sha }}
      export REPO_PATH=${{ github.repository }}
      export GH_TOKEN=${{ inputs.repo-read-token }}
      pip install -r requirements_test.txt
      python .github/wait_for_workflow_artifacts.py - ${{ inputs.build-type }}-build-${{ github.sha }}
  - name: Retrieve Docker image
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.build-type }}-build-${{ github.sha }}
      run-id: ${{ github.event.workflow_run.id }}
      github-token: ${{ inputs.repo-read-token }}
  - name: Docker load
    shell: bash
    run: |
      docker load < grafana_test_image.tar
      docker load < nginx_test_image.tar
