name: docker-test-build

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker test build
      run: |
        docker build -f Dockerfile --no-cache --target test -t grafana-test:latest .
        docker build -f Dockerfile-nginx --no-cache --target test -t nginx-test:latest .
        docker save grafana-test:latest > grafana_test_image.tar
        docker save nginx-test:latest > nginx_test_image.tar
