name: local-test

on:
  workflow_run:
    workflows:
      - docker-test-build
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Docker build
      shell: bash
      run: |
        docker build -f Dockerfile --no-cache --target test -t grafana-test:latest .
        docker build -f Dockerfile-nginx --no-cache --target test -t nginx-test:latest .
    - name: Docker compose
      shell: bash
      run: |
        export GF_PASSWORD=admin
        export DASHBOARD_UID=bdgisvc9bvym8bdashboard
        export DOMAIN_NAME=localhost
        export PUBLIC_PORT=8080
        # Dummy values (not used):
        export PUBLIC_PORT_TLS=8443
        export DB_PORT=5432
        export DB_USER=grafanauser
        export DB_NAME=grafanatest
        export DB_HOST=host.docker.internal
        export DB_PASSWORD=Test1234
        docker compose -f compose-test.yaml up --detach --force-recreate
    - name: Docker compose
      shell: bash
      run: ./.github/grafana_wait.sh
    - name: local test
      shell: bash
      run: python -m pytest test_*.py
